### ISSUE TITLE
Integration of Colorblind-friendly color palettes

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#101]
Alyssa had mentioned that it would be good to have the plots made with ACT use a colorblind-friendly palette.  This is a great idea and it should be incorporated.

**Comment by AdamTheisen** [comment]
@kenkehoe @cgodine I don't seem to be able to assign this to Alyssa, so I am just pulling you in on this issue.

**Comment by scollis** [comment]
You need to make her a collaborator in the repo.. What is her handle? I can do this.

**Comment by cgodine** [comment]
Alyssa's handle is @ajsockol.

**Comment by scollis** [comment]
Ok.. sent invite to add as a collab so she can be assigned.

**Comment by ajsockol** [comment]
Hooray, you found me! I'm going to do some research into what the different palettes could be. @kenkehoe suggested having multiple options to try and account for the different types of colorblindness, which I think is a good idea as well. Once I come up with some options I can post them here, and then look into incorporating them into ACT after we agree on a few choices.

**Comment by AdamTheisen** [comment]
#113 resolved this issue.
