### ISSUE TITLE
Plot embedded QC

### ISSUE THREAD

**Issue by kenkehoe** [ANL-DIGR/ACT#109]
We need to create a plot similar to DQ Inspector of embedded QC lining up with data. We can assign this to me.
![sgpmetE13 b1 atmos_pressure_qc_tests 20190801](https://user-images.githubusercontent.com/8261054/63614652-d6299780-c5a0-11e9-9a79-f8499e902468.png)

**Comment by AdamTheisen** [comment]
@kenkehoe Closing out as this was resolved with #118 .  Please comment if we need to reopen
