### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by nhickmon** [ANL-DIGR/ACT#117]
![Contributing_—_Atmospheric_data_Community_Toolkit_0_1_3_documentation](https://user-images.githubusercontent.com/55069891/64543841-89a5c200-d2eb-11e9-961c-7e7396df1d41.png)

In the documentation under Setting up an Environment/Install there is a typo for using ACT and its dependencies. It has is dependencies.

**Comment by AdamTheisen** [comment]
Fixed in #121
