### ISSUE TITLE
Auto Day/Night Background with 1D time Series

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#12]
Right now, the day/night background is automatically displayed if the variable is a 1d time series and there's no "ydata".  Should we remove this and leave up to users to display background?

 if ydata is None:
            self.day_night_background(subplot_index)
            ax.plot(xdata, data, '.', color=line_color)
...

**Comment by rcjackson** [comment]
Not every timeseries will lend itself to having a day/night background make sense.  This is especially true if the timestep is on the order of once or less a day. Therefore I would make it a user settable flag and disable it by defauly.



________________________________

**Comment by AdamTheisen** [comment]
This has been implemented.  Day/night background option is default to False.
