### ISSUE TITLE
Discuss guidelines for making ACT release versions

### ISSUE THREAD

**Issue by kenkehoe** [ANL-DIGR/ACT#123]
@AdamTheisen and @kenkehoe were discussing how the DQ Office installs ACT on ADC production system. We currently release off the GitHub repo with a simple RPM build. This does not track with the official ACT release version number. We will be changing to use PIP soon which should resovle this issue.

I would like to understand our guidelines on how often we create a new ACT release version so I can understand how often we need to create new RPMs and how we can get bug fixes implemented quickly.

**Comment by zssherman** [comment]
@kenkehoe A good discussion. The release process on conda-forge and pip is fairly quick, so really any time period is doable if we wanted releases every n time frame.

Py-ART I typically do a minor release when some new features, like a new kdp processing code etc, are done. micro when something breaks and needs fixing immediately. But guidelines on what we would consider for each category for ACT would be useful.

**Comment by AdamTheisen** [comment]
Just so we have it down, what if we did something like 

Micro - Patches and bug fixes
Minor - New features
Major - Large changes or shifts in the capabilities that could cause issues with older versions

Are there issues if we continue with minor releases and never actually have a major one?  Could we potentially get up to v0.100.0?

**Comment by scollis** [comment]
Super similar to what we do in Py-ART

 

We do releases for Minor and Major..

 

At the moment we are at 1.10.2

https://github.com/ARM-DOE/pyart/releases

**Comment by AdamTheisen** [comment]
I think we have a good handle on how the releases will be defined and what necessitates a release.  Closing out.
