### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#140]
It looks like the way that we are currently doing the documentation is not translating well into the sphinx generated docs.  

I.e.

obj : Xarray Dataset Object

creates this:

objXarray Dataset Object

There is no spacing between the variable name and the type.  Are we doing this the correct way @rcjackson @zssherman ?

**Comment by AdamTheisen** [comment]
For example:

https://anl-digr.github.io/ACT/API/generated/act.retrievals.calculate_precipitable_water.html

**Comment by rcjackson** [comment]
Remove the space before the colon and it should work correctly.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by AdamTheisen** [comment]
Okay, i will sort through the documentation and update.  Thanks @rcjackson!  I had a feeling that was going to be it.

**Comment by AdamTheisen** [comment]
Fixing in #141

**Comment by AdamTheisen** [comment]
Resolved
