### ISSUE TITLE
Need an avenue for users to share code that has not been vetted through publications

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#145]
There is a need to differentiate between retrievals in ACT that have been vetted through peer-reviewed publications and those that have not.  I propose we add an additional folder under retrievals for evaluation scripts.  Would calling it "eval" or "exp" for experimental work?  Other options?

@scollis @kenkehoe @zssherman @rcjackson  Thoughts?

**Comment by zssherman** [comment]
Hmm... experimental directory could work, or you could have a separate ACT branch called experimental, and once there is a publication or its peer reviewed it can be merged in via pull request.

**Comment by kenkehoe** [comment]
Umm, I know that adding a new "eval" directory is how PyART does it but that seems to have some future possible issues. I would prefer to indicate the peer-review part in the documentation so we don't need to update code in the future when we move the code from "eval" to the regular area.

Personally I would like to push back on the notion of peer-reviewed code. I worry this could have some negative connotations or reduce others from contributing. It seems this could force us to do more work reviewing the code and confrontations when a paper is submitted but not accepted yet.

**Comment by scollis** [comment]
I have feelings on this 😊

 

1) Code in Py-ART is always peer reviewed 😊 at least by the person who hits the “Accept PR”. When we have very very small changes it is permissible for the submitted to accept the PR. Only Zach and myself have this power and only Zach ever uses it. 

2) All that is needed is to ensure the code does what the code says it does.. eg 

 

def addone(val):

     return val+1

 

we just need to make sure it adds one (well and has a docstring etc)

 

I want to see ARM provide good general guidance that can be implemented by software folks in a manner that is similar to the way that it is done in the community. It works. Look at Scipy, numpy etc..

**Comment by AdamTheisen** [comment]
I'm going to close this out.  I do think ensuring that we have folks use "Reference" in the docstring and supply the paper, tech report, etc that it comes will take care of this requirement.
