### ISSUE TITLE
Wind rose and sounding plots.

### ISSUE THREAD

**Issue by rcjackson** [ANL-DIGR/ACT#15]
In addition to a TimeSeriesDisplay, we need to have a WindRoseDisplay and a SkewTDisplay object. This needs to be done by the ARM-ASR PI meeting as a demonstration that shows that Paytsar is able to use it for her data.

For Skew-T plots, I am thinking of introducing metpy as a dependency since it does these really well.

**Comment by rcjackson** [comment]
Also, a WindBarbPlot for the timeseries. Perhaps make this a separate option for timeseries display.

**Comment by AdamTheisen** [comment]
This has been implemented.  Closing out.
