### ISSUE TITLE
Combine clean.py into armfiles.py

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#159]
The clean.py script is very ARM-centric and so i'm wondering if it would make sense to include in the armfiles.py file instead of a stand-alone one.  Or, as another option, since it is very qc centric, that it be moved into the qc directory and titled appropriately if it is mainly for ARM QC.  @kenkehoe thoughts?

**Comment by kenkehoe** [comment]
Sure we can move it anywhere that makes sense. I think QC would be appropriate.

**Comment by kenkehoe** [comment]
You can assign this to me. I don't think I have that power.
