### ISSUE TITLE
reading csv into xarray

### ISSUE THREAD

**Issue by kenkehoe** [ANL-DIGR/ACT#18]
Adam mentioned the need to allow data to be in a more general format for this repo to be broader to the open source community. A quick search for how to read CSV data into xarray didn't show any results, but it does look like pandas can read CSV. Can we create a module or example using pandas to show how the CSV data will be read in with pandas and then converted to xarray with DataFrame.to_xarray()?

**Comment by AdamTheisen** [comment]
Sorry, I was wrong there. I was thinking of the read function for pandas which will be easy to convert to xarray.  I think that would be fairly simple to add

**Comment by AdamTheisen** [comment]
@rcjackson Are you the only one that can close out an Issue?

**Comment by rcjackson** [comment]
@AdamTheisen I invited you and @scollis to be collaborators. I think that makes it to where you can open/close issues.

**Comment by AdamTheisen** [comment]
Perfect!  Thanks @rcjackson
