### ISSUE TITLE
Docs has wrong location to install from

### ISSUE THREAD

**Issue by rcjackson** [ANL-DIGR/ACT#23]
In the docs, it says to clone from the AdamTheisen repository, but it's actually better to clone from the ANL-DIGR repository. In the end, we'll fix this whole issue with pip and conda packaging, but this is a reminder for me to change that part of the docs tomorrow.

**Comment by jkyrouac** [comment]
Also might want to add minimum version of Python to install doc. I got an error initially because I did not have Python 3.
