### ISSUE TITLE
License and Author Files Incorrect

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#28]
It looks like the AUTHOR and LICENSE files from my initial build using the scientific cookie cutter were pulled over.  We should update these accordingly.

**Comment by AdamTheisen** [comment]
@scollis @rcjackson Who do we need to go through at ANL in order to get a license set?

**Comment by rcjackson** [comment]
You have to fill out an ANL-1032 in Xink to get the licensing done.

________________________________

**Comment by AdamTheisen** [comment]
Thanks!  That looks to be a longer form so I'll start on the paperwork tomorrow.

**Comment by AdamTheisen** [comment]
#50 Should update this to use the BSD-3 license until the paperwork goes through Argonne.

**Comment by scollis** [comment]
We will eventually .. for now look at Pyarts and adapt

**Comment by AdamTheisen** [comment]
License has been approved.  Closing out
