### ISSUE TITLE
Standard Way of Sharing Example Codes without having them as actual examples.

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#29]
What's the standard practice for sharing scripts that use the ACT library?  We don't necessarily want to have a full example for display on the website.  Is there another way to do this as part of the repo or would we want to handle this separately?

**Comment by scollis** [comment]
A notebooks directory 

-sent from a mobile device-

**Comment by AdamTheisen** [comment]
Is there a certain way we should do this or just at a notebooks dir into the examples dir?

**Comment by AdamTheisen** [comment]
Adding dir in commit #77
