### ISSUE TITLE
What to do when file not found

### ISSUE THREAD

**Issue by kenkehoe** [ANL-DIGR/ACT#38]
I would like to change the base behavior when a file is not found with io.read_netcdf() to catch the FileNotFound error and instead just return a value of None. This makes more logical sense to me to use the reading function to go check if the file exists. We do a lot of stuff depending on availability of files and having to wrap everything in a try seems excessive. I would suggest adding a verbose option to make a print statement optional if the file is not found, but not make that the default option. If this is OK I'll make the update.

**Comment by AdamTheisen** [comment]
That sounds good to me

**Comment by rcjackson** [comment]
@kenkehoe thank you for the PR fixing this issue! Closing.
