### ISSUE TITLE
Best way to handle geographic plots (ship/aircraft data).

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#45]
We need to determine what library would be best for plotting up maps with plane/ship tracks overlaid.

**Comment by zssherman** [comment]
Most likely Cartopy and probably xarray, but I'll look into it more. Most mapping is all cartopy now as basemap is no mas.

**Comment by rcjackson** [comment]
I would use cartopy to do it. It would not be hard to implement for any dataset with 1D lat/lon data. I'll work on this after the SAGE workshop...plan on submitting my PR for Skew-T project.

**Comment by AdamTheisen** [comment]
Ken was talking about working on this tomorrow possibly so let's coordinate

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rcjackson** [comment]
Sounds good. We can talk about it tomorrow at the meeting.

________________________________

**Comment by kenkehoe** [comment]
I'm looking into this now.

**Comment by scollis** [comment]
100% cartopy 

-sent from a mobile device-

**Comment by kenkehoe** [comment]
I think we have this implemented. Should we close this?
