### ISSUE TITLE
Way to set absolute limits for time series plot

### ISSUE THREAD

**Issue by kenkehoe** [ANL-DIGR/ACT#51]
I am putting in a feature request to have a way to set an absolute limit when making a time series plot so a single very large or small value will not make the plot unusable. I have some ideas on how to implement. 

- Thinking not used as default
- can add to min or max independently
- can add absolute values or percentage of mean, mode or median
- Will indicate on plot that the range displayed does not show all values

I'll try to get to this soon.

**Comment by kenkehoe** [comment]
This is merged into current master under #52 , but I need to look into adding comment on the plot that some data was not plotted.

**Comment by AdamTheisen** [comment]
@kenkehoe What do you think, is this good to close out now?

**Comment by kenkehoe** [comment]
Yeah I was going to add a comment to the plot but I don't think that is necessary anymore. Let's just close this out.
