### ISSUE TITLE
Roadmap Discussion

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#53]
It seems like a lot of the initial framework is developed.  It seems like a good time to discuss what else we envision adding to this repo in the near and far term.

**Comment by AdamTheisen** [comment]
What we have

1D/2D plotting capability
Skew-T
Wind Rose
NetCDF Reader (ARM)
CSV Reader (ICERAD, AOT, ANL Met Tower)

Potential Items to Add
Model Data (Bobby had mentioned this and was going to look into it)
Surface Maps of Data at SGP (MET/ECOR/EBBR)
MPL Corrections and Co/Cross Ratio Calculation
Mentor Retrieval (MPL Aerosol?)

What else?

**Comment by Trekev** [comment]
Another potential idea for discussion, but may be outside the scope of the toolkit at this stage of the game.  A lot of government agencies have operational data that's output as text format on a regular basis(Thinking of ASOS stations and balloon observations).  These are often used in the research community as well.  Would creating ways to import this data have a benefit and fit into the scope of the ACT?

**Comment by kenkehoe** [comment]
I think having multiple data format readers will be the most important one for the general user community. That should open things up to a broader audience. May also want to look into writers that will output in different formats to accommodate different organizations and their requirements. For example netCDF3 vs. netCDF4, CF vs. ARM vs. someone else. Eventually CF will get their act together and allow netCDF4 with string array attributes. When that day comes it will be revolutionary!

Also a general expanding of the utilities modules to do things like matching time grids and interpolation would be nice. Most of that stuff can be done with xarray calls but it takes some doing to get the syntax right and that wold help users find more use for the ACT repo. 

Also, should this have direct interface with PyArt more?

**Comment by AdamTheisen** [comment]
I started looking into the NEON data and I think histograms would be a big help with some of that data

**Comment by AdamTheisen** [comment]
Just to update here, many of the items listed here have been added or have been discussed and do not fit within the scope.  The roadmap is being worked on and will be finalized soon.  We will post once complete and close this out.

**Comment by AdamTheisen** [comment]
Roadmap has been created and will be uploaded
