### ISSUE TITLE
Stability Indices for BBSS data 

### ISSUE THREAD

**Issue by Trekev** [ANL-DIGR/ACT#55]
It may be useful to have a way to calculate stability indices for the BBSS data.  Perhaps a way to output a table with the plot or a separate file.

**Comment by rcjackson** [comment]
I think this would probably go under the "retrieval" module. I envision a first entry in that module with "calc_stability_indices" that returns a dictionary with CAPE, CIN, LI, etc.

**Comment by scollis** [comment]
Very cool.. Easy hook to MetPy
