### ISSUE TITLE
read_netcdf function causes segfault when attempting to read in a day of radar data

### ISSUE THREAD

**Issue by atkingtornado** [ANL-DIGR/ACT#64]
It seems that the read_netcdf function in act.io.armfiles causes a segfault when reading in radar data. Perhaps because of the large file sizes? the specific case that causes the segfault is reading in the following list of files:

['/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.000013.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.010019.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.020010.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.030009.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.040011.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.050013.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.060019.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.070007.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.080020.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.090004.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.100010.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.110016.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.120011.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.130013.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.140004.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.150010.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.160019.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.170014.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.180013.nc', '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.190008.nc']

The function call looks like:
`read_netcdf(files,
                            return_None=True,
                            mask_and_scale=False,
                            data_vars='minimal')
`
where data_vars is simple the list of variables

**Comment by AdamTheisen** [comment]
Ah yes.   I ran into something similar when trying to use xarray to read in kazr data for the DQ Office.  In the radar.py library script I ended up using the old DataDateQuery function to read in the kazr data and that seemed to work.  I wonder if in some instances we need to loop through the files instead of using open_mfdataset.

I will try looking into this a bit and see.

**Comment by kenkehoe** [comment]
This direct call

filename = '/data/datastream/sgp/sgpkazrcfrgeC1.a1/sgpkazrcfrgeC1.a1.20190225.*.nc'
ds_object = xr.open_mfdataset(filename, drop_variables=drop_variables)

works for me.

I think it's an issue with the current option set of parallel=True in the ACT reading module. I suggest taking that option off the default in ACT and let it be passed through by the users.

**Comment by kenkehoe** [comment]
I'm going to suggest we pull parallel=True out of the currently set keywords in the xr call. I am still getting good results with concat_dim='time' in the call. But we should put that keyword in the read_netcdf() function so we have the ability to update if needed.

**Comment by AdamTheisen** [comment]
Just submitted pull request #65  to make this change
