### ISSUE TITLE
New QC not showing up in Documentation

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#86]
I don't see any of the new QC features documented in the ACT docs.  

https://anl-digr.github.io/ACT/

@rcjackson @zssherman  it looks like @kenkehoe has things documented fairly well.  Is there something we need to do to get it to show up?

**Comment by rcjackson** [comment]
We might have to go into the .rst files and make sure that they are referring to the docstrings in the code.

________________________________

**Comment by zssherman** [comment]
Might need to add qcfilter to the __init__ file docs. I don't see it referenced. Some functions use single quotes instead of doubles, but I don't think that would effect it at all.

**Comment by kenkehoe** [comment]
qcfilter imports qctests. Could that be part of the issue?

**Comment by AdamTheisen** [comment]
@zssherman where exactly is that init file you are referring to?

**Comment by zssherman** [comment]
@AdamTheisen For example, in the retrievals where calculate_stability_indices :

"""
===============================
act.retrievals (act.retrievals)
===============================
.. currentmodule:: act.retrievals
This module contains various retrievals for ARM datsets.
.. autosummary::
    :toctree: generated/
    calculate_stability_indicies
"""

from .stability_indices import calculate_stability_indicies
 
So maybe under :toctree: generated/ qcfilter functions need to be added. Similar to what seen in the retrieval __init__

**Comment by AdamTheisen** [comment]
Documentation is showing up now.

**Comment by kenkehoe** [comment]
I'm not sure this is resolved. The classes are listed in the documentation but my doc strings are not showing up nor all the method names. I am happy to look into solving this but I don't understand enough to know where to start. I tried running the doc generation locally and ran into issues. Can we reopen this to remind me to look into again?

**Comment by AdamTheisen** [comment]
@kenkehoe Check out ACT/docs/source/API/plotting.rst.  This may give you a good lead into what to do for the QC part.  

When you make changes there, you can run "make html" in the ACT/docs folder.  Once that completes you can check out the html page by opening ACT/docs/build/html/index.html

**Comment by AdamTheisen** [comment]
Note, I also think you need to add documentation to the QCTests class.

**Comment by kenkehoe** [comment]
I have documentation to the QCTests class but it is not showing up. Does anyone have suggestions on how to fix this? Looks like the function documentation is showing up but none of my method documentation is being processed.

**Comment by AdamTheisen** [comment]
@kenkehoe The only thing I can see at the moment is that the QCTests class is not initialized.  See the Display class in plotting/plot.py.  It has documentation on the class and an initializer

    def __init__(self, obj, subplot_shape=(1,), ds_name=None,
                 subplot_kw=None, **kwargs):

**Comment by AdamTheisen** [comment]
I am also seeing warnings when I try and build the documentation for the qc 

/anaconda3/lib/python3.7/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example: in the docstring of <function parse_bit at 0x1c1ce85048> in /Users/atheisen/Code/ACT/act/qc/qcfilter.py.
  warn(msg)

/anaconda3/lib/python3.7/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example in the docstring of <function set_bit at 0x1c1ce19ea0> in /Users/atheisen/Code/ACT/act/qc/qcfilter.py.
  warn(msg)

/anaconda3/lib/python3.7/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example: in the docstring of <function unset_bit at 0x1c1ce7c2f0> in /Users/atheisen/Code/ACT/act/qc/qcfilter.py.
  warn(msg)

/anaconda3/lib/python3.7/site-packages/numpydoc/docscrape.py:424: UserWarning: Unknown section Example in the docstring of <function rolling_window at 0x1c1ce7c158> in /Users/atheisen/Code/ACT/act/qc/qctests.py.

**Comment by kenkehoe** [comment]
OK thanks. I've made a few changes and things are not fixed but better. I'll keep looking into it.

**Comment by kenkehoe** [comment]
I needed to list each method to get the QC to show up but it is there now. We can close this and I'll look into why I need to list the methods another day.
